New log file opened at Tue Jun 28 16:39:01 CEST 2016 by 4924@NbKatrin
Taking next connection to: 54323
New client attempting to connect on port: 54324-54323
  Address = /192.168.12.1:54323
This client on port 54324 has uuid 94f3afd8-dfd4-43dc-9a7b-3a8de4929f3d configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-94f3afd8-dfd4-43dc-9a7b-3a8de4929f3d
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
New client attempting to connect on port: 54549-54323
  Address = /192.168.12.1:54323
Handshake exception on socket: 54549
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 54323
New client attempting to connect on port: 54550-54323
  Address = /192.168.12.1:54323
This client on port 54550 has uuid b40f5253-d506-4779-b670-fb283bbdbdd0 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-94f3afd8-dfd4-43dc-9a7b-3a8de4929f3d, play-fork-run-b40f5253-d506-4779-b670-fb283bbdbdd0
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 54323
Checking to see if clients are empty...
No non-daemon clients connected after 3 min. Shutting down.
Server socket thread exiting.
0 clients open, will close them...
All client sockets have been closed.
Closing the 4924@NbKatrin logs at Tue Jun 28 17:09:31 CEST 2016, goodbye.
